version: "3"
services:
  KunlunXPanel:
    image: "kunlun-xpanel:1.1.1"
    build:
      context: ./
      dockerfile: ./KunlunXPanel/Dockerfile
    restart: always
    container_name: "kunlun-xpanel-dev"
    ports:
      - "8989:9528"
    volumes:
      - /Users/helayd/Documents/GitHub/Kunlun-XPanel/KunlunXPanel:/KunlunXPanel:rw
    environment:
      TZ: "Asia/Shanghai"
    command: npm run dev
  php:
    image: php:7.4.11-fpm-alpine3.12
    build: './KunlunMonitor'
    volumes:
      - ./:/var/www/html/
  apache:
    image: httpd:2.4-alpine
    build: './compose/apache'
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./compose/apache/:/usr/local/apache2/conf.d


