version: "3"
services:
  php:
    image: php:7.4.11-fpm-alpine3.12
    build: './KunlunMonitor'
    networks:
      - mynet
    volumes:
      - ./:/var/www/html/
  apache:
    image: httpd:2.4-alpine
    build: './compose/apache'
    depends_on:
      - php
    networks:
      - mynet
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./compose/apache/:/usr/local/apache2/conf.d
networks:
  mynet:
