version: "3"
services:
  php:
    image: php:7.4.11-fpm-alpine3.12
    build: './KunlunMonitor'
    volumes:
      - ./:/var/www/html/
    networks:
      csl:
        ipv4_address: 172.19.0.7
  apache-kunlun-server:
    image: httpd:2.4-alpine
    build: './compose/apacheserver'
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
      - ./compose/apacheserver/:/usr/local/apache2/conf.d
    networks:
      csl:
        ipv4_address: 172.19.0.6

  apache-kunlun-client:
    image: httpd:2.4-alpine
    build: './compose/apacheclient'
    ports:
      - "8086:80"
    volumes:
      - ./KunlunXPanel/dist:/var/www/html/
      - ./compose/apacheclient/:/usr/local/apache2/conf.d
    networks:
      csl:
        ipv4_address: 172.19.0.8
networks:
  csl:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
