global:
scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgres"
    static_configs:
      - targets: ["192.168.0.128:9187"]
  - job_name: "mysql"
    static_configs:
      - targets: ["192.168.0.128:9104"]
  - job_name: "node"
    static_configs:
      - targets: ["192.168.0.128:9100"]